= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v1.0.1...v1.0.2++[1.0.2^] (2021-03-26)

=== Continuous Integration

* enable Vagrant-based testing using GitHub Actions
(https://github.com/saltstack-formulas/openvpn-formula/commit/290c8b48e405e03c224ec28496aa135e1d336810[290c8b4^])
* *kitchen+ci:* use latest pre-salted images (after CVE) [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/deb3ac1d7bf8f52dc92f3f0b09009e669558f1cb[deb3ac1^])
* *windows:* use `kitchen.windows.yml`
(https://github.com/saltstack-formulas/openvpn-formula/commit/76491c4cb0fd12d8a44a9ffd7d5a3c66f768db0c[76491c4^])

=== Tests

* *_mapdata:* add verification file for Windows 2016 Server
(https://github.com/saltstack-formulas/openvpn-formula/commit/dda60f07ec955db038a0eaaaa842c0f8bc08a1d1[dda60f0^])
* standardise use of `share` suite & `_mapdata` state [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/c247b83f47161e59289617467957f8e07f472ff1[c247b83^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v1.0.0...v1.0.1++[1.0.1^] (2021-02-22)

=== Continuous Integration

* *gemfile+lock:* use `ssf` customised `kitchen-docker` repo [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/a69b6134e6a0b8a77aed6078e24394ba236808a0[a69b613^])
* *github+windows:* install and use Chef embedded Ruby
(https://github.com/saltstack-formulas/openvpn-formula/commit/f1cc1b9e2676dbae6366518788beece49de30f8c[f1cc1b9^])
* *kitchen+gitlab-ci:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/8eeb4295f193cdaca85aea3954f7194c36dfe2b6[8eeb429^])

=== Tests

* *kitchen+windows:* remove no longer needed workaround
(https://github.com/saltstack-formulas/openvpn-formula/commit/470f4d6eb77e6281356d518b5ae83230f2ae1657[470f4d6^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.8...v1.0.0++[1.0.0^] (2021-02-14)

=== Continuous Integration

* *pre-commit:* update hook for `rubocop` [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/4d772627d43eb1ce051fc6549639ca826fad9481[4d77262^])

=== Features

* *map:* the YAML files must not use any Jinja
(https://github.com/saltstack-formulas/openvpn-formula/commit/4db7d6f6b33ea6741a5bdc67265c51cefde61a75[4db7d6f^])
* *map:* update to v5 `map.jinja`
(https://github.com/saltstack-formulas/openvpn-formula/commit/c28acb9c0cf9125d955095d35fc1023113186509[c28acb9^])

=== BREAKING CHANGES

* *map:* `map.jinja` now export a generic `mapdata` variable
* *map:* The parameters per grains are now under `openvpn/parameters/`

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.7...v0.16.8++[0.16.8^] (2021-01-29)

=== Continuous Integration

* *kitchen+gitlab:* update for new pre-salted images
(https://github.com/saltstack-formulas/openvpn-formula/commit/0b969018bacdd565170528636f4b976466ef1cae[0b96901^])

=== Tests

* *services_spec:* add test for `be_installed`
(https://github.com/saltstack-formulas/openvpn-formula/commit/fe7784331d6fe29f5e8312627b9ba40d14497fb9[fe77843^])
* *tumbleweed:* add map verification file
(https://github.com/saltstack-formulas/openvpn-formula/commit/ff5a9cfbfa7a98d8742351224bac239b79c4528c[ff5a9cf^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.6...v0.16.7++[0.16.7^] (2021-01-14)

=== Bug Fixes

* *_mapdata:* ensure map data is directly under `values`
(https://github.com/saltstack-formulas/openvpn-formula/commit/0f96d554e7fef9d467b023ac24e8de45f0355766[0f96d55^])

=== Tests

* *_mapdata:* update for `_mapdata/init.sls` change
(https://github.com/saltstack-formulas/openvpn-formula/commit/241d349f3a63ddea03ec0692df8b9ca61abb452c[241d349^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.5...v0.16.6++[0.16.6^] (2020-12-23)

=== Code Refactoring

* *map:* use top-level `values:` key in `map.jinja` dumps
(https://github.com/saltstack-formulas/openvpn-formula/commit/132e38afd496b3e75b8e117c6c8468d00e6e1ea5[132e38a^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.4...v0.16.5++[0.16.5^] (2020-12-22)

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/f15efd16b04fa54bfd808431b1bbd645b74dd9bf[f15efd1^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/901af81f2bdb9962bf5f1806c26faee9598fde6a[901af81^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/openvpn-formula/commit/01cd86afa7d26b86507cf3ee894b9d4d42fa94f0[01cd86a^])
* *kitchen+gitlab:* update for new pre-salted images [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/a0fdc618b009180a67f33a634699bc34e8ed163c[a0fdc61^])

=== Tests

* *_mapdata:* fix existing verification files
(https://github.com/saltstack-formulas/openvpn-formula/commit/b61d904e9ad95d94cbaf589d2db9b2a324fc9602[b61d904^])
* *_mapdata:* generate remaining verification files
(https://github.com/saltstack-formulas/openvpn-formula/commit/97ccbb303f10a23ae741c3c5af9da6a5307ba7e3[97ccbb3^])
* *map:* standardise `map.jinja` verification
(https://github.com/saltstack-formulas/openvpn-formula/commit/a755b4d28202f9b55c25ac616157a7f959947abd[a755b4d^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.3...v0.16.4++[0.16.4^] (2020-10-30)

=== Continuous Integration

* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/740ba4e80e01a724b7833ee6b3d7e66740ced795[740ba4e^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/95bbd5eee34dd7ae36642ea38f2fc388c385cb30[95bbd5e^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/92e02f2b549ed599786bb08562dc4bc60df84c49[92e02f2^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/44e040d3a143c7d3a2ad6805ae1f42e261bb7f32[44e040d^])
* avoid `init_environment` failing due to
saltstack/salthttps://github.com/saltstack-formulas/openvpn-formula/issues/57628[#57628]
(https://github.com/saltstack-formulas/openvpn-formula/commit/398932b8332b701b6a1430018629d097b2f41155[398932b^])

=== Tests

* *map:* verify `map.jinja` dump using `_mapdata` state
(https://github.com/saltstack-formulas/openvpn-formula/commit/ecac1b107f8a5309b803cb7fe41d1802b427b5fe[ecac1b1^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.2...v0.16.3++[0.16.3^] (2020-06-10)

=== Bug Fixes

* *tap-adapter.ps1:* work with alternate name `Local Area Connection`
(https://github.com/saltstack-formulas/openvpn-formula/commit/372b3b6d80ef5ede742961bca44d726d16249646[372b3b6^])

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/0aa9fd6d93533d824f4c6d144474d6721dd1bca6[0aa9fd6^])
* *github:* add Windows testing using Actions
(https://github.com/saltstack-formulas/openvpn-formula/commit/2d4b79c5f8afe73eeeef187e63d9613bbf7bd793[2d4b79c^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/6eb1b4437df9e2b8bb3171f8811bcf1d091113d9[6eb1b44^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/9e7aa34a499b30eab737295ae4649e510365deab[9e7aa34^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/80930cdb479fb9f2eef7a0044b93e08fabb1d804[80930cd^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/4099f15a1440bf7d9dfde707137593d9cf495d02[4099f15^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/5900915e5b86cdad1fdca9163873e1fd9ee44f98[5900915^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.1...v0.16.2++[0.16.2^] (2019-12-16)

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/ed6b7f0c0d6a9171eadca2ffbc3682e24a3e346b[ed6b7f0^])

=== Tests

* add test for auth-nocache option
(https://github.com/saltstack-formulas/openvpn-formula/commit/79c10556dee2431d93ce9d678d002ec1036d219b[79c1055^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.16.0...v0.16.1++[0.16.1^] (2019-12-06)

=== Bug Fixes

* *auth_nocache:* fix typo in client template
(https://github.com/saltstack-formulas/openvpn-formula/commit/c8f0971d148be9efb8405ff7eef5bbe4eeae9ea8[c8f0971^]),
closes
https://github.com/saltstack-formulas/openvpn-formula/issues/125[#125^]

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.15.4...v0.16.0++[0.16.0^] (2019-11-29)

=== Continuous Integration

* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/ea3336af6f3657d24c0657173f07ed224140a46b[ea3336a^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/bb43f31450ccb48601ef61620a42c9904c502e0d[bb43f31^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/667bc1f04b7e96bd2c5cdce8a91d76552d34c884[667bc1f^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/9d63e36fa618df6d966ad1278bfa64153db0a9fe[9d63e36^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/d2f7fe24a19033b8db907be89f184b26b128b326[d2f7fe2^])

=== Features

* *auth_nocache:* support for auth-nocache
(https://github.com/saltstack-formulas/openvpn-formula/commit/c21b7f52cc0ce24c96cf1b9173a9fda9e3eb7ae7[c21b7f5^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.15.3...v0.15.4++[0.15.4^] (2019-11-06)

=== Bug Fixes

* *adapters:* call `adapters.sls` in `init.sls`
(https://github.com/saltstack-formulas/openvpn-formula/commit/3ebcbe93f8245fb435c3e9af91853930683e16b1[3ebcbe9^])
* *dhparams:* allow generating Diffie Hellman parameters on Windows
(https://github.com/saltstack-formulas/openvpn-formula/commit/3802024a69d5e4008d192084d10858511f3dca4d[3802024^])
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/81d922d7a3053c309e0e8f965825063df576921e[81d922d^])

=== Continuous Integration

* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/83e00e1c4d64e86f79b2fa9cb6e8be0490cdb83e[83e00e1^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/06a09f29e187f9b01865b582eff944c30e294302[06a09f2^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/4eb9d3bed2df51360822db639c2085414bfc13e3[4eb9d3b^])
* *travis:* merge `rubocop` linter into main `lint` job
(https://github.com/saltstack-formulas/openvpn-formula/commit/9f82955081169661780b8a236c1b20da15bf9aa2[9f82955^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/d465b4f6063ab78864cf2f25a26c339e74b64c18[d465b4f^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/openvpn-formula/commit/70dab6c4ee9d9d69f80c81ae314df0d97c79114e[70dab6c^])

=== Documentation

* add steps required for testing using Vagrant
(https://github.com/saltstack-formulas/openvpn-formula/commit/0229d1446f89d0ebe44f70b1834a0a9aa8cb68e1[0229d14^])
* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/8703eb50a6ea7505716b2350e34b88f894a4e725[8703eb5^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/a72049f738005c95548db7e3b87847d8ce741eda[a72049f^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/26838e5ccd0400390bb3a2eb29741d36a8992ac3[26838e5^])

=== Tests

* *windows:* add local testing of Windows using Vagrant/Virtualbox
(https://github.com/saltstack-formulas/openvpn-formula/commit/96c300125dfa86c67d14e09f772b453eddde7c84[96c3001^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.15.2...v0.15.3++[0.15.3^] (2019-10-10)

=== Bug Fixes

* *config.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/openvpn-formula/commit/1b3f7f6[1b3f7f6^])
* *ifconfig_pool_persist.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/openvpn-formula/commit/6969083[6969083^])
* *map.jinja:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/openvpn-formula/commit/eabfc57[eabfc57^])

=== Continuous Integration

* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/b76dcc9[b76dcc9^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/0db9651[0db9651^])
* *platform:* add `arch-base-latest` (commented out for now) [skip ci]
(https://github.com/saltstack-formulas/openvpn-formula/commit/75d7aaa[75d7aaa^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/openvpn-formula/commit/d7f1607[d7f1607^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.15.1...v0.15.2++[0.15.2^] (2019-09-25)

=== Bug Fixes

* *service:* stop old service only if name is different to new service
(https://github.com/saltstack-formulas/openvpn-formula/commit/1724dfd[1724dfd^]),
closes
https://github.com/saltstack-formulas/openvpn-formula/issues/119[#119^]

=== Continuous Integration

* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/openvpn-formula/commit/e94c9ba[e94c9ba^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.15.0...v0.15.1++[0.15.1^] (2019-09-21)

=== Bug Fixes

* *repo:* provide EPEL repo configuration for `Amazon Linux-2`
(https://github.com/saltstack-formulas/openvpn-formula/commit/bfb29bd[bfb29bd^])

=== Continuous Integration

* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/openvpn-formula/commit/5e02797[5e02797^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/openvpn-formula/commit/a437b3b[a437b3b^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.14.2...v0.15.0++[0.15.0^] (2019-09-07)

=== Features

* *auth_gen_token:* support for auth-gen-token
(https://github.com/saltstack-formulas/openvpn-formula/commit/333edd7[333edd7^])
* *syslog:* support for syslog
(https://github.com/saltstack-formulas/openvpn-formula/commit/24b370c[24b370c^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.14.1...v0.14.2++[0.14.2^] (2019-09-06)

=== Documentation

* *pillar.example:* update with quoted "yes" for comp-lzo
(https://github.com/saltstack-formulas/openvpn-formula/commit/1b49b24[1b49b24^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.14.0...v0.14.1++[0.14.1^] (2019-09-01)

=== Bug Fixes

* *config:* configurable distinction between server and client services
(https://github.com/saltstack-formulas/openvpn-formula/commit/18c4c4a[18c4c4a^])
* *config:* sub-mappings for client and server
(https://github.com/saltstack-formulas/openvpn-formula/commit/b30b23d[b30b23d^])
* *service:* make sure the now obsolete systemd services are disabled
(https://github.com/saltstack-formulas/openvpn-formula/commit/2dfae46[2dfae46^])
* *service:* removed trailing whitespace
(https://github.com/saltstack-formulas/openvpn-formula/commit/85d2458[85d2458^])
* *test:* drop ' then$'
(https://github.com/saltstack-formulas/openvpn-formula/commit/62c2f70[62c2f70^])
* *test:* dropped redundant permission checks
(https://github.com/saltstack-formulas/openvpn-formula/commit/9c3ea71[9c3ea71^])

=== Continuous Integration

* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/openvpn-formula/commit/2577535[2577535^])

=== Tests

* *kitchen:* debian and ubuntu use different paths now
(https://github.com/saltstack-formulas/openvpn-formula/commit/dfd784e[dfd784e^])
* *pillar:* set 'status' to fix kitchen tests
(https://github.com/saltstack-formulas/openvpn-formula/commit/07bb5b6[07bb5b6^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.13.1...v0.14.0++[0.14.0^] (2019-08-15)

=== Bug Fixes

* *network_manager_networks:* properly override port
(https://github.com/saltstack-formulas/openvpn-formula/commit/1d58ec6[1d58ec6^])
* *network_manager_networks:* reduced pillar.get calls
(https://github.com/saltstack-formulas/openvpn-formula/commit/7ee9eed[7ee9eed^])

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/openvpn-formula/commit/4355ac6[4355ac6^])

== link:++https://github.com/saltstack-formulas/openvpn-formula/compare/v0.13.0...v0.13.1++[0.13.1^] (2019-07-19)

=== Bug Fixes

* *centos:* install OpenSSL on CentOS
(https://github.com/saltstack-formulas/openvpn-formula/commit/7e4c8d6[7e4c8d6^])
* *centos-6:* has only _one_ service 'openvpn'
(https://github.com/saltstack-formulas/openvpn-formula/commit/3d5723d[3d5723d^])
* *config:* script-security is a common option
(https://github.com/saltstack-formulas/openvpn-formula/commit/b1b482c[b1b482c^])
* *config:* set tls-auth and tls-crypt independentyl of ta_content
(https://github.com/saltstack-formulas/openvpn-formula/commit/d3787b6[d3787b6^])
* *debian-ish:* root owns the logs
(https://github.com/saltstack-formulas/openvpn-formula/commit/3276d3b[3276d3b^])
* *fedora:* honor working directory & service name
(https://github.com/saltstack-formulas/openvpn-formula/commit/4f8e899[4f8e899^])
* *freebsd:* load if_tap module
(https://github.com/saltstack-formulas/openvpn-formula/commit/d63581a[d63581a^])
* *jinja:* don't call pillar.get
(https://github.com/saltstack-formulas/openvpn-formula/commit/33b98f5[33b98f5^])
* *logging:* set replace=False and add dependencies for log files
(https://github.com/saltstack-formulas/openvpn-formula/commit/9b71fcf[9b71fcf^])
* *macros:* use openvpn/macros.jinja
(https://github.com/saltstack-formulas/openvpn-formula/commit/637387e[637387e^])
* *service:* use OS-specific service name in multi-service setups
(https://github.com/saltstack-formulas/openvpn-formula/commit/b16756c[b16756c^])
* *specs:* use boolean operator
(https://github.com/saltstack-formulas/openvpn-formula/commit/89fa956[89fa956^])

=== Continuous Integration

* *cleanup:* dropped obsolete opensuse-leap-15 workaround
(https://github.com/saltstack-formulas/openvpn-formula/commit/1e1719d[1e1719d^])
* *kitchen:* add kitchen file + testinfra
(https://github.com/saltstack-formulas/openvpn-formula/commit/9c5ee26[9c5ee26^])
* *kitchen:* rename pillar
(https://github.com/saltstack-formulas/openvpn-formula/commit/4122fc0[4122fc0^])
* *kitchen:* test/config/pillars: add jinja for user on debian >= 9
(https://github.com/saltstack-formulas/openvpn-formula/commit/3c7f947[3c7f947^])
* *kitchen+travis:* modify matrix to include `develop` platform
(https://github.com/saltstack-formulas/openvpn-formula/commit/91b5798[91b5798^])
* *specs:* increased readability
(https://github.com/saltstack-formulas/openvpn-formula/commit/b2c9cf1[b2c9cf1^])
* *test data:* moved Pillar test data
(https://github.com/saltstack-formulas/openvpn-formula/commit/2fff1ee[2fff1ee^])
* *testing:* added bin/kitchen
(https://github.com/saltstack-formulas/openvpn-formula/commit/15bea7b[15bea7b^])
* *travis:* exclude Fedora 29 from Travis CI
(https://github.com/saltstack-formulas/openvpn-formula/commit/4a1f9ed[4a1f9ed^])
* *travis:* test based on template-formula and
https://github.com/saltstack-formulas/openvpn-formula/issues/98[#98^]
(https://github.com/saltstack-formulas/openvpn-formula/commit/b9daf9b[b9daf9b^])
